name: publish
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - 'master'       # Run the workflow when pushing to the main branch
  pull_request:
    branches:
      - '*'          # Run the workflow for all pull requests
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  create_nuget:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using MinVer

    - name: Print Working Directory
      run: pwd

    - name: List Files
      run: Get-ChildItem -Recurse

    # Install the .NET SDK indicated in the global.json file
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.412'

    # Restore dependencies to ensure assets files are generated
    - name: Restore Dependencies
      run: dotnet restore

    - name: Check InnoAndLogic.Shared Version
      id: check_shared_version
      run: |
        $localVersion = (Get-Content ./InnoAndLogic.Shared/InnoAndLogic.Shared.csproj | Select-String -Pattern '<Version>(.*?)</Version>' | ForEach-Object { $_.Matches.Groups[1].Value }).Trim()
        $nugetVersion = dotnet list package --include-prerelease --source https://api.nuget.org/v3/index.json | Select-String -Pattern "InnoAndLogic.Shared" | ForEach-Object { ($_ -split '\s+')[1] }
        if ($localVersion -eq $nugetVersion) {
          Write-Host "Version $localVersion of InnoAndLogic.Shared is already published on NuGet. Skipping packaging."
          echo "skip_shared=true" >> $GITHUB_ENV
        } else {
          Write-Host "Version $localVersion of InnoAndLogic.Shared is not published on NuGet. Proceeding with packaging."
          echo "skip_shared=false" >> $GITHUB_ENV
        }

    # Build the solution to ensure all projects are compiled
    - name: Build Solution
      run: dotnet build --configuration Release

    # Create the NuGet package in the folder from the environment variable NuGetDirectory
    - name: Create NuGet Packages
      if: env.skip_shared == 'false'
      run: dotnet pack ./InnoAndLogic.Shared/InnoAndLogic.Shared.csproj --configuration Release --include-symbols --output ${{ env.NuGetDirectory }}

    - name: Create NuGet Packages for Persistence
      run: dotnet pack ./InnoAndLogic.Persistence/InnoAndLogic.Persistence.csproj --configuration Release --include-symbols --output ${{ env.NuGetDirectory }}

    # List build output
    - name: List Build Output
      run: |
        echo "Listing build output for InnoAndLogic.Shared:"
        Get-ChildItem InnoAndLogic.Shared\bin\Release\net8.0 -Recurse
        echo "Listing build output for InnoAndLogic.Persistence:"
        Get-ChildItem InnoAndLogic.Persistence\bin\Release\net8.0 -Recurse
        echo "Listing build output for InnoAndLogic.DistributedCaching:"
        Get-ChildItem InnoAndLogic.DistributedCaching\bin\Release\net8.0 -Recurse

    # List NuGet Directory contents
    - name: List NuGet Directory Contents
      run: |
        echo "Listing contents of NuGet directory:"
        Get-ChildItem ${{ env.NuGetDirectory }} -Recurse

    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: |
          ${{ env.NuGetDirectory }}/*.nupkg
          ${{ env.NuGetDirectory }}/*.snupkg

  run_test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.412'
    - name: Clean and Restore
      run: |
        dotnet clean
        dotnet restore
    - name: Run tests
      run: dotnet test --configuration Release

  deploy:
    # Publish only when a new release is created
    if: github.event_name == 'release'
    runs-on: windows-latest
    needs: [ create_nuget, run_test ]
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: nuget
        path: ${{ env.NuGetDirectory }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4

    - name: Publish NuGet package
      run: |
        foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg, *.snupkg)) {
            dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        }
